### PR TITLE
Add UART serial example, restructure examples

### PR DESCRIPTION
**Pull request by holmbuar**
This PR will refactor the examples structure, adding a non-working UART serial example, with its own custom transport. The purpose of this example is to be able to run the Pico in a debug session, from VS Code. 

Currently, the example connects to the Micro-ROS agent successfully, then stalls after only 1 `msg.data` published. Build this example with `make uart_example` in Debug mode.

The original USB example is in its own folder, and can be built by `make usb_example` in Release mode, then copy `.uf2` to Pico. This example is working normally.

The reason for creating this draft PR is to discuss further why the UART serial custom transport makes the Pico stall. Previous discussions in https://github.com/micro-ROS/micro_ros_raspberrypi_pico_sdk/issues/942 and https://github.com/micro-ROS/micro_ros_raspberrypi_pico_sdk/issues/937.

### CODE REVIEW

**Comment by holmbuar** [comment]
@pablogs9 could you please assist by wiring up two Picos, or getting a [Pi Debug Probe](https://www.raspberrypi.com/documentation/microcontrollers/debug-probe.html), and try to replicate the UART serial issue?

**Comment by pablogs9** [comment]
Does this PR have the UART issue?

**Comment by holmbuar** [comment]
yes

**Comment by holmbuar** [comment]
@pablogs9 I'm closing this, as the original transport works just fine. My goof, sorry. I got valuable assistance from the Raspberry Pi forum. I will add a PR for the README, with UART config example.

**Comment by pablogs9** [comment]
Thanks!

**Comment by holmbuar** [comment]
I'd still suggest you getting a Debug Probe, for simple validation of future issues :computer:

**Pull request closed without merging**
